// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NoiseHandshakePayload.proto
package p2p.noise;

public final class NoiseHandshakePayloadProtos {
    private NoiseHandshakePayloadProtos() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface NoiseHandshakePayloadOrBuilder extends
            // @@protoc_insertion_point(interface_extends:NoiseHandshakePayload)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required bytes identity_key = 1;</code>
         *
         * @return Whether the identityKey field is set.
         */
        boolean hasIdentityKey();

        /**
         * <code>required bytes identity_key = 1;</code>
         *
         * @return The identityKey.
         */
        com.google.protobuf.ByteString getIdentityKey();

        /**
         * <code>required bytes identity_sig = 2;</code>
         *
         * @return Whether the identitySig field is set.
         */
        boolean hasIdentitySig();

        /**
         * <code>required bytes identity_sig = 2;</code>
         *
         * @return The identitySig.
         */
        com.google.protobuf.ByteString getIdentitySig();

        /**
         * <code>required bytes data = 3;</code>
         *
         * @return Whether the data field is set.
         */
        boolean hasData();

        /**
         * <code>required bytes data = 3;</code>
         *
         * @return The data.
         */
        com.google.protobuf.ByteString getData();
    }

    /**
     * Protobuf type {@code NoiseHandshakePayload}
     */
    public static final class NoiseHandshakePayload extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:NoiseHandshakePayload)
            NoiseHandshakePayloadOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use NoiseHandshakePayload.newBuilder() to construct.
        private NoiseHandshakePayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private NoiseHandshakePayload() {
            identityKey_ = com.google.protobuf.ByteString.EMPTY;
            identitySig_ = com.google.protobuf.ByteString.EMPTY;
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new NoiseHandshakePayload();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return unknownFields;
        }

        private NoiseHandshakePayload(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            bitField0_ |= 0x00000001;
                            identityKey_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            identitySig_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            data_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return NoiseHandshakePayloadProtos.internal_static_NoiseHandshakePayload_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return NoiseHandshakePayloadProtos.internal_static_NoiseHandshakePayload_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            NoiseHandshakePayloadProtos.NoiseHandshakePayload.class, NoiseHandshakePayloadProtos.NoiseHandshakePayload.Builder.class);
        }

        private int bitField0_;
        public static final int IDENTITY_KEY_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString identityKey_;

        /**
         * <code>required bytes identity_key = 1;</code>
         *
         * @return Whether the identityKey field is set.
         */
        @java.lang.Override
        public boolean hasIdentityKey() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required bytes identity_key = 1;</code>
         *
         * @return The identityKey.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getIdentityKey() {
            return identityKey_;
        }

        public static final int IDENTITY_SIG_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString identitySig_;

        /**
         * <code>required bytes identity_sig = 2;</code>
         *
         * @return Whether the identitySig field is set.
         */
        @java.lang.Override
        public boolean hasIdentitySig() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>required bytes identity_sig = 2;</code>
         *
         * @return The identitySig.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getIdentitySig() {
            return identitySig_;
        }

        public static final int DATA_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString data_;

        /**
         * <code>required bytes data = 3;</code>
         *
         * @return Whether the data field is set.
         */
        @java.lang.Override
        public boolean hasData() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>required bytes data = 3;</code>
         *
         * @return The data.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            if (!hasIdentityKey()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasIdentitySig()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasData()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeBytes(1, identityKey_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeBytes(2, identitySig_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeBytes(3, data_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, identityKey_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, identitySig_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, data_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof NoiseHandshakePayloadProtos.NoiseHandshakePayload)) {
                return super.equals(obj);
            }
            NoiseHandshakePayloadProtos.NoiseHandshakePayload other = (NoiseHandshakePayloadProtos.NoiseHandshakePayload) obj;

            if (hasIdentityKey() != other.hasIdentityKey()) {
                return false;
            }
            if (hasIdentityKey()) {
                if (!getIdentityKey()
                        .equals(other.getIdentityKey())) {
                    return false;
                }
            }
            if (hasIdentitySig() != other.hasIdentitySig()) {
                return false;
            }
            if (hasIdentitySig()) {
                if (!getIdentitySig()
                        .equals(other.getIdentitySig())) {
                    return false;
                }
            }
            if (hasData() != other.hasData()) {
                return false;
            }
            if (hasData()) {
                if (!getData()
                        .equals(other.getData())) {
                    return false;
                }
            }
            if (!unknownFields.equals(other.unknownFields)) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasIdentityKey()) {
                hash = (37 * hash) + IDENTITY_KEY_FIELD_NUMBER;
                hash = (53 * hash) + getIdentityKey().hashCode();
            }
            if (hasIdentitySig()) {
                hash = (37 * hash) + IDENTITY_SIG_FIELD_NUMBER;
                hash = (53 * hash) + getIdentitySig().hashCode();
            }
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(NoiseHandshakePayloadProtos.NoiseHandshakePayload prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code NoiseHandshakePayload}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:NoiseHandshakePayload)
                NoiseHandshakePayloadProtos.NoiseHandshakePayloadOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return NoiseHandshakePayloadProtos.internal_static_NoiseHandshakePayload_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return NoiseHandshakePayloadProtos.internal_static_NoiseHandshakePayload_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                NoiseHandshakePayloadProtos.NoiseHandshakePayload.class, NoiseHandshakePayloadProtos.NoiseHandshakePayload.Builder.class);
            }

            // Construct using NoiseHandshakePayloadOuterClass.NoiseHandshakePayload.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                identityKey_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                identitySig_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                data_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return NoiseHandshakePayloadProtos.internal_static_NoiseHandshakePayload_descriptor;
            }

            @java.lang.Override
            public NoiseHandshakePayloadProtos.NoiseHandshakePayload getDefaultInstanceForType() {
                return NoiseHandshakePayloadProtos.NoiseHandshakePayload.getDefaultInstance();
            }

            @java.lang.Override
            public NoiseHandshakePayloadProtos.NoiseHandshakePayload build() {
                NoiseHandshakePayloadProtos.NoiseHandshakePayload result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public NoiseHandshakePayloadProtos.NoiseHandshakePayload buildPartial() {
                NoiseHandshakePayloadProtos.NoiseHandshakePayload result = new NoiseHandshakePayloadProtos.NoiseHandshakePayload(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.identityKey_ = identityKey_;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.identitySig_ = identitySig_;
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.data_ = data_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof NoiseHandshakePayloadProtos.NoiseHandshakePayload) {
                    return mergeFrom((NoiseHandshakePayloadProtos.NoiseHandshakePayload) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(NoiseHandshakePayloadProtos.NoiseHandshakePayload other) {
                if (other == NoiseHandshakePayloadProtos.NoiseHandshakePayload.getDefaultInstance()) {
                    return this;
                }
                if (other.hasIdentityKey()) {
                    setIdentityKey(other.getIdentityKey());
                }
                if (other.hasIdentitySig()) {
                    setIdentitySig(other.getIdentitySig());
                }
                if (other.hasData()) {
                    setData(other.getData());
                }
                mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                if (!hasIdentityKey()) {
                    return false;
                }
                if (!hasIdentitySig()) {
                    return false;
                }
                if (!hasData()) {
                    return false;
                }
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                NoiseHandshakePayloadProtos.NoiseHandshakePayload parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (NoiseHandshakePayloadProtos.NoiseHandshakePayload) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.ByteString identityKey_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes identity_key = 1;</code>
             *
             * @return Whether the identityKey field is set.
             */
            @java.lang.Override
            public boolean hasIdentityKey() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>required bytes identity_key = 1;</code>
             *
             * @return The identityKey.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getIdentityKey() {
                return identityKey_;
            }

            /**
             * <code>required bytes identity_key = 1;</code>
             *
             * @param value The identityKey to set.
             * @return This builder for chaining.
             */
            public Builder setIdentityKey(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                identityKey_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes identity_key = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearIdentityKey() {
                bitField0_ = (bitField0_ & ~0x00000001);
                identityKey_ = getDefaultInstance().getIdentityKey();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString identitySig_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes identity_sig = 2;</code>
             *
             * @return Whether the identitySig field is set.
             */
            @java.lang.Override
            public boolean hasIdentitySig() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>required bytes identity_sig = 2;</code>
             *
             * @return The identitySig.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getIdentitySig() {
                return identitySig_;
            }

            /**
             * <code>required bytes identity_sig = 2;</code>
             *
             * @param value The identitySig to set.
             * @return This builder for chaining.
             */
            public Builder setIdentitySig(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                identitySig_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes identity_sig = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearIdentitySig() {
                bitField0_ = (bitField0_ & ~0x00000002);
                identitySig_ = getDefaultInstance().getIdentitySig();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes data = 3;</code>
             *
             * @return Whether the data field is set.
             */
            @java.lang.Override
            public boolean hasData() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>required bytes data = 3;</code>
             *
             * @return The data.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <code>required bytes data = 3;</code>
             *
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes data = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearData() {
                bitField0_ = (bitField0_ & ~0x00000004);
                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:NoiseHandshakePayload)
        }

        // @@protoc_insertion_point(class_scope:NoiseHandshakePayload)
        private static final NoiseHandshakePayloadProtos.NoiseHandshakePayload DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new NoiseHandshakePayloadProtos.NoiseHandshakePayload();
        }

        public static NoiseHandshakePayloadProtos.NoiseHandshakePayload getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<NoiseHandshakePayload>
                PARSER = new com.google.protobuf.AbstractParser<>() {
            @java.lang.Override
            public NoiseHandshakePayload parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new NoiseHandshakePayload(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<NoiseHandshakePayload> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<NoiseHandshakePayload> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public NoiseHandshakePayloadProtos.NoiseHandshakePayload getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_NoiseHandshakePayload_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_NoiseHandshakePayload_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\033NoiseHandshakePayload.proto\"Q\n\025NoiseHa" +
                        "ndshakePayload\022\024\n\014identity_key\030\001 \002(\014\022\024\n\014" +
                        "identity_sig\030\002 \002(\014\022\014\n\004data\030\003 \002(\014"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_NoiseHandshakePayload_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_NoiseHandshakePayload_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_NoiseHandshakePayload_descriptor,
                new java.lang.String[]{"IdentityKey", "IdentitySig", "Data",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
